# Crypto Configuration for Production EMR Fabric Network
# Defines the structure for generating cryptographic materials
# Compliant with read111.md multi-organization requirements

OrdererOrgs:
  - Name: Orderer
    Domain: emr.com
    EnableNodeOUs: true
    Specs:
      - Hostname: orderer
        SANS:
          - localhost
          - 127.0.0.1
          - orderer.emr.com

PeerOrgs:
  # Hospital1 Organization
  - Name: Hospital1
    Domain: hospital1.emr.com
    EnableNodeOUs: true
    Template:
      Count: 2
      SANS:
        - localhost
        - 127.0.0.1
        - "{{.Hostname}}.hospital1.emr.com"
    Users:
      Count: 3

  # Hospital2 Organization  
  - Name: Hospital2
    Domain: hospital2.emr.com
    EnableNodeOUs: true
    Template:
      Count: 2
      SANS:
        - localhost
        - 127.0.0.1
        - "{{.Hostname}}.hospital2.emr.com"
    Users:
      Count: 3

  # Regulator Organization
  - Name: Regulator
    Domain: regulator.emr.com
    EnableNodeOUs: true
    Template:
      Count: 1
      SANS:
        - localhost
        - 127.0.0.1
        - "{{.Hostname}}.regulator.emr.com"
    Users:
      Count: 2
