# Alertmanager Configuration for EMR Blockchain System
# Healthcare-compliant alert routing and escalation
# Supports multiple notification channels and escalation policies

global:
  smtp_smarthost: '${SMTP_HOST}:${SMTP_PORT}'
  smtp_from: 'emr-alerts@${DOMAIN}'
  smtp_auth_username: '${SMTP_USERNAME}'
  smtp_auth_password: '${SMTP_PASSWORD}'
  smtp_require_tls: true
  
  # Slack configuration
  slack_api_url: '${SLACK_WEBHOOK_URL}'
  
  # PagerDuty configuration
  pagerduty_url: 'https://events.pagerduty.com/v2/enqueue'

# Template files for custom alert formatting
templates:
  - '/etc/alertmanager/templates/*.tmpl'

# Alert routing configuration
route:
  group_by: ['alertname', 'cluster', 'service']
  group_wait: 30s
  group_interval: 5m
  repeat_interval: 12h
  receiver: 'default-receiver'
  
  routes:
    # Critical security alerts - immediate escalation
    - match:
        severity: critical
        category: security
      receiver: 'security-team-critical'
      group_wait: 0s
      repeat_interval: 5m
      continue: true

    # HIPAA compliance violations - immediate escalation
    - match:
        compliance: hipaa
      receiver: 'compliance-team'
      group_wait: 0s
      repeat_interval: 15m
      continue: true

    # System availability alerts
    - match:
        category: availability
      receiver: 'ops-team-critical'
      group_wait: 30s
      repeat_interval: 10m
      routes:
        - match:
            severity: critical
          receiver: 'ops-team-pager'
          group_wait: 0s
          repeat_interval: 5m

    # Performance degradation alerts
    - match:
        category: performance
      receiver: 'ops-team-performance'
      group_wait: 2m
      repeat_interval: 30m

    # Blockchain-specific alerts
    - match:
        category: blockchain
      receiver: 'blockchain-team'
      group_wait: 1m
      repeat_interval: 15m
      routes:
        - match:
            severity: critical
          receiver: 'blockchain-team-critical'
          group_wait: 0s
          repeat_interval: 5m

    # Storage and IPFS alerts
    - match:
        category: storage
      receiver: 'storage-team'
      group_wait: 2m
      repeat_interval: 20m

    # Database alerts
    - match:
        category: database
      receiver: 'database-team'
      group_wait: 1m
      repeat_interval: 15m
      routes:
        - match:
            severity: critical
          receiver: 'database-team-critical'
          group_wait: 0s
          repeat_interval: 5m

    # Resource exhaustion alerts
    - match:
        category: resources
      receiver: 'infrastructure-team'
      group_wait: 5m
      repeat_interval: 1h

    # Backup and disaster recovery alerts
    - match:
        category: backup
      receiver: 'backup-team'
      group_wait: 10m
      repeat_interval: 6h

    - match:
        category: disaster_recovery
      receiver: 'dr-team'
      group_wait: 1h
      repeat_interval: 24h

# Inhibition rules to prevent alert spam
inhibit_rules:
  # Inhibit non-critical alerts when critical alerts are firing
  - source_match:
      severity: 'critical'
    target_match:
      severity: 'warning'
    equal: ['alertname', 'instance']

  # Inhibit individual component alerts when system is down
  - source_match:
      alertname: 'EMRSystemDown'
    target_match_re:
      alertname: '.*'
    equal: ['instance']

  # Inhibit performance alerts when availability alerts are active
  - source_match:
      category: 'availability'
    target_match:
      category: 'performance'
    equal: ['instance']

# Receiver configurations
receivers:
  # Default receiver for unmatched alerts
  - name: 'default-receiver'
    email_configs:
      - to: 'ops-team@${DOMAIN}'
        subject: '[EMR Alert] {{ .GroupLabels.alertname }}'
        body: |
          {{ range .Alerts }}
          Alert: {{ .Annotations.summary }}
          Description: {{ .Annotations.description }}
          Severity: {{ .Labels.severity }}
          Instance: {{ .Labels.instance }}
          Time: {{ .StartsAt }}
          {{ end }}

  # Security team - critical alerts
  - name: 'security-team-critical'
    email_configs:
      - to: 'security-team@${DOMAIN}'
        subject: '[CRITICAL SECURITY] {{ .GroupLabels.alertname }}'
        body: |
          🚨 CRITICAL SECURITY ALERT 🚨
          
          {{ range .Alerts }}
          Alert: {{ .Annotations.summary }}
          Description: {{ .Annotations.description }}
          Impact: {{ .Annotations.impact }}
          Runbook: {{ .Annotations.runbook_url }}
          Time: {{ .StartsAt }}
          {{ end }}
    slack_configs:
      - channel: '#security-alerts'
        title: '🚨 Critical Security Alert'
        text: |
          {{ range .Alerts }}
          *Alert:* {{ .Annotations.summary }}
          *Description:* {{ .Annotations.description }}
          *Impact:* {{ .Annotations.impact }}
          *Runbook:* {{ .Annotations.runbook_url }}
          {{ end }}
        color: 'danger'
    pagerduty_configs:
      - routing_key: '${PAGERDUTY_SECURITY_KEY}'
        description: '{{ .GroupLabels.alertname }}'
        severity: 'critical'

  # Compliance team
  - name: 'compliance-team'
    email_configs:
      - to: 'compliance@${DOMAIN}'
        subject: '[COMPLIANCE VIOLATION] {{ .GroupLabels.alertname }}'
        body: |
          ⚖️ COMPLIANCE VIOLATION DETECTED ⚖️
          
          {{ range .Alerts }}
          Alert: {{ .Annotations.summary }}
          Description: {{ .Annotations.description }}
          Compliance Type: {{ .Labels.compliance }}
          Impact: {{ .Annotations.impact }}
          Runbook: {{ .Annotations.runbook_url }}
          Time: {{ .StartsAt }}
          {{ end }}
    slack_configs:
      - channel: '#compliance-alerts'
        title: '⚖️ Compliance Violation'
        color: 'danger'

  # Operations team - critical system alerts
  - name: 'ops-team-critical'
    email_configs:
      - to: 'ops-team@${DOMAIN}'
        subject: '[CRITICAL] {{ .GroupLabels.alertname }}'
        body: |
          🔥 CRITICAL SYSTEM ALERT 🔥
          
          {{ range .Alerts }}
          Alert: {{ .Annotations.summary }}
          Description: {{ .Annotations.description }}
          Impact: {{ .Annotations.impact }}
          Runbook: {{ .Annotations.runbook_url }}
          Time: {{ .StartsAt }}
          {{ end }}
    slack_configs:
      - channel: '#ops-critical'
        title: '🔥 Critical System Alert'
        color: 'danger'

  # Operations team - pager for immediate response
  - name: 'ops-team-pager'
    pagerduty_configs:
      - routing_key: '${PAGERDUTY_OPS_KEY}'
        description: '{{ .GroupLabels.alertname }}'
        severity: 'critical'
        details:
          summary: '{{ range .Alerts }}{{ .Annotations.summary }}{{ end }}'
          impact: '{{ range .Alerts }}{{ .Annotations.impact }}{{ end }}'
          runbook: '{{ range .Alerts }}{{ .Annotations.runbook_url }}{{ end }}'

  # Operations team - performance alerts
  - name: 'ops-team-performance'
    email_configs:
      - to: 'ops-team@${DOMAIN}'
        subject: '[PERFORMANCE] {{ .GroupLabels.alertname }}'
    slack_configs:
      - channel: '#ops-performance'
        title: '📊 Performance Alert'
        color: 'warning'

  # Blockchain team
  - name: 'blockchain-team'
    email_configs:
      - to: 'blockchain-team@${DOMAIN}'
        subject: '[BLOCKCHAIN] {{ .GroupLabels.alertname }}'
    slack_configs:
      - channel: '#blockchain-alerts'
        title: '⛓️ Blockchain Alert'
        color: 'warning'

  # Blockchain team - critical
  - name: 'blockchain-team-critical'
    email_configs:
      - to: 'blockchain-team@${DOMAIN}'
        subject: '[CRITICAL BLOCKCHAIN] {{ .GroupLabels.alertname }}'
    slack_configs:
      - channel: '#blockchain-critical'
        title: '🚨 Critical Blockchain Alert'
        color: 'danger'
    pagerduty_configs:
      - routing_key: '${PAGERDUTY_BLOCKCHAIN_KEY}'
        description: '{{ .GroupLabels.alertname }}'
        severity: 'critical'

  # Storage team
  - name: 'storage-team'
    email_configs:
      - to: 'storage-team@${DOMAIN}'
        subject: '[STORAGE] {{ .GroupLabels.alertname }}'
    slack_configs:
      - channel: '#storage-alerts'
        title: '💾 Storage Alert'
        color: 'warning'

  # Database team
  - name: 'database-team'
    email_configs:
      - to: 'database-team@${DOMAIN}'
        subject: '[DATABASE] {{ .GroupLabels.alertname }}'
    slack_configs:
      - channel: '#database-alerts'
        title: '🗄️ Database Alert'
        color: 'warning'

  # Database team - critical
  - name: 'database-team-critical'
    email_configs:
      - to: 'database-team@${DOMAIN}'
        subject: '[CRITICAL DATABASE] {{ .GroupLabels.alertname }}'
    slack_configs:
      - channel: '#database-critical'
        title: '🚨 Critical Database Alert'
        color: 'danger'
    pagerduty_configs:
      - routing_key: '${PAGERDUTY_DATABASE_KEY}'
        description: '{{ .GroupLabels.alertname }}'
        severity: 'critical'

  # Infrastructure team
  - name: 'infrastructure-team'
    email_configs:
      - to: 'infrastructure@${DOMAIN}'
        subject: '[INFRASTRUCTURE] {{ .GroupLabels.alertname }}'
    slack_configs:
      - channel: '#infrastructure-alerts'
        title: '🏗️ Infrastructure Alert'
        color: 'warning'

  # Backup team
  - name: 'backup-team'
    email_configs:
      - to: 'backup-team@${DOMAIN}'
        subject: '[BACKUP] {{ .GroupLabels.alertname }}'
    slack_configs:
      - channel: '#backup-alerts'
        title: '💿 Backup Alert'
        color: 'warning'

  # Disaster recovery team
  - name: 'dr-team'
    email_configs:
      - to: 'dr-team@${DOMAIN}'
        subject: '[DISASTER RECOVERY] {{ .GroupLabels.alertname }}'
    slack_configs:
      - channel: '#dr-alerts'
        title: '🆘 Disaster Recovery Alert'
        color: 'warning'
