apiVersion: apps/v1
kind: Deployment
metadata:
  name: emr-frontend-production
  namespace: emr-production
  labels:
    app: emr-frontend-production
    environment: production
spec:
  replicas: 3
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 1
      maxSurge: 1
  selector:
    matchLabels:
      app: emr-frontend-production
  template:
    metadata:
      labels:
        app: emr-frontend-production
        environment: production
    spec:
      containers:
      - name: frontend
        image: IMAGE_TAG_FRONTEND
        ports:
        - containerPort: 80
          name: http
        env:
        - name: REACT_APP_API_URL
          valueFrom:
            configMapKeyRef:
              name: emr-config-production
              key: REACT_APP_API_URL
        - name: REACT_APP_TITLE
          valueFrom:
            configMapKeyRef:
              name: emr-config-production
              key: REACT_APP_TITLE
        - name: REACT_APP_VERSION
          value: "1.0.0"
        - name: BUILD_TIME
          value: "${BUILD_TIME}"
        resources:
          requests:
            memory: "256Mi"
            cpu: "200m"
          limits:
            memory: "512Mi"
            cpu: "400m"
        livenessProbe:
          httpGet:
            path: /health
            port: 80
          initialDelaySeconds: 30
          periodSeconds: 30
          timeoutSeconds: 10
          failureThreshold: 3
        readinessProbe:
          httpGet:
            path: /health
            port: 80
          initialDelaySeconds: 10
          periodSeconds: 10
          timeoutSeconds: 5
          failureThreshold: 3
      restartPolicy: Always

---
apiVersion: v1
kind: Service
metadata:
  name: emr-frontend-service-production
  namespace: emr-production
  labels:
    app: emr-frontend-production
spec:
  type: ClusterIP
  ports:
  - port: 80
    targetPort: 80
    protocol: TCP
    name: http
  selector:
    app: emr-frontend-production

---
# Horizontal Pod Autoscaler
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: emr-frontend-hpa-production
  namespace: emr-production
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: emr-frontend-production
  minReplicas: 3
  maxReplicas: 8
  metrics:
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: 70
  - type: Resource
    resource:
      name: memory
      target:
        type: Utilization
        averageUtilization: 80