apiVersion: v1
kind: Secret
metadata:
  name: emr-secrets-production
  namespace: emr-production
type: Opaque
data:
  # Base64编码的敏感信息 (实际部署时需要替换为真实的生产环境密钥)
  DB_PASSWORD: cHJvZF9wYXNzd29yZA==  # prod_password (需要替换)
  DB_ROOT_PASSWORD: cHJvZF9yb290X3Bhc3N3b3Jk  # prod_root_password (需要替换)
  JWT_SECRET: cHJvZF9qd3Rfc2VjcmV0XzEyMw==  # prod_jwt_secret_123 (需要替换)
  ENCRYPTION_KEY: cHJvZF9lbmNyeXB0aW9uX2tleV8xMjM=  # prod_encryption_key_123 (需要替换)
  IPFS_API_KEY: cHJvZF9pcGZzX2FwaV9rZXk=  # prod_ipfs_api_key (需要替换)
  REDIS_PASSWORD: cHJvZF9yZWRpc19wYXNzd29yZA==  # prod_redis_password (需要替换)
  
---
apiVersion: v1
kind: Secret
metadata:
  name: mysql-root-password-production
  namespace: emr-production
type: Opaque
data:
  password: cHJvZF9yb290X3Bhc3N3b3Jk  # prod_root_password (需要替换)