apiVersion: v1
kind: Namespace
metadata:
  name: blockchain-emr
  labels:
    name: blockchain-emr
    environment: production
    app: blockchain-emr-system
---
apiVersion: v1
kind: ResourceQuota
metadata:
  name: blockchain-emr-quota
  namespace: blockchain-emr
spec:
  hard:
    requests.cpu: "20"
    requests.memory: 40Gi
    limits.cpu: "40"
    limits.memory: 80Gi
    persistentvolumeclaims: "20"
    services: "20"
    secrets: "20"
    configmaps: "20"
---
apiVersion: v1
kind: LimitRange
metadata:
  name: blockchain-emr-limits
  namespace: blockchain-emr
spec:
  limits:
  - default:
      cpu: "1"
      memory: "2Gi"
    defaultRequest:
      cpu: "100m"
      memory: "256Mi"
    type: Container
  - default:
      storage: "10Gi"
    type: PersistentVolumeClaim
