apiVersion: v1
kind: Secret
metadata:
  name: blockchain-emr-secrets
  namespace: blockchain-emr
  labels:
    app: blockchain-emr
type: Opaque
data:
  # Database credentials (base64 encoded)
  MYSQL_USER: ZW1yX3VzZXI=  # emr_user
  MYSQL_PASSWORD: cHJvZF9wYXNzd29yZF8xMjM=  # prod_password_123
  MYSQL_ROOT_PASSWORD: cHJvZF9yb290X3Bhc3N3b3JkXzEyMw==  # prod_root_password_123
  MYSQL_REPLICATION_PASSWORD: cmVwbGljYXRpb25fcGFzc3dvcmRfMTIz  # replication_password_123
  
  # Redis password
  REDIS_PASSWORD: cmVkaXNfcGFzc3dvcmRfMTIz  # redis_password_123
  
  # JWT and encryption secrets
  JWT_SECRET: c3VwZXJfc2VjdXJlX2p3dF9rZXlfZm9yX3Byb2R1Y3Rpb25fdXNlX29ubHk=  # super_secure_jwt_key_for_production_use_only
  ENCRYPTION_KEY: ZW5jcnlwdGlvbl9rZXlfMzJfY2hhcnNfbG9uZw==  # encryption_key_32_chars_long
  MASTER_ENCRYPTION_KEY: bWFzdGVyX2VuY3J5cHRpb25fa2V5XzY0X2NoYXJhY3RlcnNfbG9uZ19mb3JfcHJvZHVjdGlvbl91c2Vfb25seQ==  # master_encryption_key_64_characters_long_for_production_use_only
  SESSION_SECRET: c2Vzc2lvbl9zZWNyZXRfa2V5X2Zvcl9wcm9kdWN0aW9u  # session_secret_key_for_production
  
  # IPFS cluster secret
  IPFS_CLUSTER_SECRET: aXBmc19jbHVzdGVyX3NlY3JldF82NF9jaGFyYWN0ZXJzX2xvbmdfZm9yX3Byb2R1Y3Rpb25fdXNlX29ubHk=  # ipfs_cluster_secret_64_characters_long_for_production_use_only
  
  # External service credentials
  EMAIL_SMTP_USER: bm9yZXBseUBibG9ja2NoYWluLWVtci5jb20=  # noreply@blockchain-emr.com
  EMAIL_SMTP_PASSWORD: ZW1haWxfcGFzc3dvcmRfMTIz  # email_password_123
  
  # SMS service credentials
  SMS_ACCOUNT_SID: dHdpbGlvX2FjY291bnRfc2lk  # twilio_account_sid
  SMS_AUTH_TOKEN: dHdpbGlvX2F1dGhfdG9rZW4=  # twilio_auth_token
  
  # AWS credentials for backups
  AWS_ACCESS_KEY_ID: YXdzX2FjY2Vzc19rZXlfaWQ=  # aws_access_key_id
  AWS_SECRET_ACCESS_KEY: YXdzX3NlY3JldF9hY2Nlc3Nfa2V5  # aws_secret_access_key
  
  # Fabric CA admin credentials
  FABRIC_CA_ADMIN_PASSWORD: ZmFicmljX2NhX2FkbWluX3Bhc3N3b3Jk  # fabric_ca_admin_password
  
  # Monitoring credentials
  GRAFANA_PASSWORD: Z3JhZmFuYV9hZG1pbl9wYXNzd29yZA==  # grafana_admin_password
---
apiVersion: v1
kind: Secret
metadata:
  name: tls-secret
  namespace: blockchain-emr
  labels:
    app: nginx
type: kubernetes.io/tls
data:
  # TLS certificate and key (base64 encoded)
  # These should be replaced with actual certificates in production
  tls.crt: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCi4uLgotLS0tLUVORCBDRVJUSUZJQ0FURS0tLS0t
  tls.key: LS0tLS1CRUdJTiBQUklWQVRFIEtFWS0tLS0tCi4uLgotLS0tLUVORCBQUklWQVRFIEtFWS0tLS0t
---
apiVersion: v1
kind: Secret
metadata:
  name: registry-secret
  namespace: blockchain-emr
  labels:
    app: blockchain-emr
type: kubernetes.io/dockerconfigjson
data:
  # Docker registry credentials for private images
  .dockerconfigjson: eyJhdXRocyI6eyJyZWdpc3RyeS5leGFtcGxlLmNvbSI6eyJ1c2VybmFtZSI6InVzZXIiLCJwYXNzd29yZCI6InBhc3MiLCJhdXRoIjoiZFhObGNqcHdZWE56In19fQ==
