# Kubernetes命名空间配置
apiVersion: v1
kind: Namespace
metadata:
  name: emr-namespace
  labels:
    name: emr-namespace
    app: blockchain-emr
    environment: production
  annotations:
    description: "区块链电子病历系统生产环境命名空间"
    created-by: "EMR DevOps Team"
    version: "1.0.0"
---
# 资源配额
apiVersion: v1
kind: ResourceQuota
metadata:
  name: emr-resource-quota
  namespace: emr-namespace
spec:
  hard:
    requests.cpu: "4"
    requests.memory: 8Gi
    limits.cpu: "8"
    limits.memory: 16Gi
    persistentvolumeclaims: "10"
    pods: "20"
    services: "10"
    secrets: "10"
    configmaps: "10"
---
# 网络策略
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: emr-network-policy
  namespace: emr-namespace
spec:
  podSelector: {}
  policyTypes:
  - Ingress
  - Egress
  ingress:
  - from:
    - namespaceSelector:
        matchLabels:
          name: emr-namespace
    - namespaceSelector:
        matchLabels:
          name: ingress-nginx
  egress:
  - to:
    - namespaceSelector:
        matchLabels:
          name: emr-namespace
  - to: []
    ports:
    - protocol: TCP
      port: 53
    - protocol: UDP
      port: 53
  - to: []
    ports:
    - protocol: TCP
      port: 443
    - protocol: TCP
      port: 80