# Configuration Transaction (configtx) for Production EMR Network
# Defines channel configuration and policies
# Compliant with read111.md multi-organization requirements

Organizations:
  # Orderer Organization
  - &OrdererOrg
    Name: OrdererOrg
    ID: OrdererMSP
    MSPDir: crypto-config/ordererOrganizations/emr.com/msp
    Policies:
      Readers:
        Type: Signature
        Rule: "OR('OrdererMSP.member')"
      Writers:
        Type: Signature
        Rule: "OR('OrdererMSP.member')"
      Admins:
        Type: Signature
        Rule: "OR('OrdererMSP.admin')"
    OrdererEndpoints:
      - orderer.emr.com:7050

  # Hospital1 Organization
  - &Hospital1
    Name: Hospital1MSP
    ID: Hospital1MSP
    MSPDir: crypto-config/peerOrganizations/hospital1.emr.com/msp
    Policies:
      Readers:
        Type: Signature
        Rule: "OR('Hospital1MSP.admin', 'Hospital1MSP.peer', 'Hospital1MSP.client')"
      Writers:
        Type: Signature
        Rule: "OR('Hospital1MSP.admin', 'Hospital1MSP.client')"
      Admins:
        Type: Signature
        Rule: "OR('Hospital1MSP.admin')"
      Endorsement:
        Type: Signature
        Rule: "OR('Hospital1MSP.peer')"
    AnchorPeers:
      - Host: peer0.hospital1.emr.com
        Port: 7051

  # Hospital2 Organization
  - &Hospital2
    Name: Hospital2MSP
    ID: Hospital2MSP
    MSPDir: crypto-config/peerOrganizations/hospital2.emr.com/msp
    Policies:
      Readers:
        Type: Signature
        Rule: "OR('Hospital2MSP.admin', 'Hospital2MSP.peer', 'Hospital2MSP.client')"
      Writers:
        Type: Signature
        Rule: "OR('Hospital2MSP.admin', 'Hospital2MSP.client')"
      Admins:
        Type: Signature
        Rule: "OR('Hospital2MSP.admin')"
      Endorsement:
        Type: Signature
        Rule: "OR('Hospital2MSP.peer')"
    AnchorPeers:
      - Host: peer0.hospital2.emr.com
        Port: 9051

  # Regulator Organization
  - &Regulator
    Name: RegulatorMSP
    ID: RegulatorMSP
    MSPDir: crypto-config/peerOrganizations/regulator.emr.com/msp
    Policies:
      Readers:
        Type: Signature
        Rule: "OR('RegulatorMSP.admin', 'RegulatorMSP.peer', 'RegulatorMSP.client')"
      Writers:
        Type: Signature
        Rule: "OR('RegulatorMSP.admin', 'RegulatorMSP.client')"
      Admins:
        Type: Signature
        Rule: "OR('RegulatorMSP.admin')"
      Endorsement:
        Type: Signature
        Rule: "OR('RegulatorMSP.peer')"
    AnchorPeers:
      - Host: peer0.regulator.emr.com
        Port: 11051

Capabilities:
  Channel: &ChannelCapabilities
    V2_0: true
  Orderer: &OrdererCapabilities
    V2_0: true
  Application: &ApplicationCapabilities
    V2_0: true

Application: &ApplicationDefaults
  Organizations:
  Policies:
    Readers:
      Type: ImplicitMeta
      Rule: "ANY Readers"
    Writers:
      Type: ImplicitMeta
      Rule: "ANY Writers"
    Admins:
      Type: ImplicitMeta
      Rule: "MAJORITY Admins"
    LifecycleEndorsement:
      Type: ImplicitMeta
      Rule: "MAJORITY Endorsement"
    Endorsement:
      Type: ImplicitMeta
      Rule: "MAJORITY Endorsement"
  Capabilities:
    <<: *ApplicationCapabilities

Orderer: &OrdererDefaults
  OrdererType: etcdraft
  Addresses:
    - orderer.emr.com:7050
  EtcdRaft:
    Consenters:
      - Host: orderer.emr.com
        Port: 7050
        ClientTLSCert: crypto-config/ordererOrganizations/emr.com/orderers/orderer.emr.com/tls/server.crt
        ServerTLSCert: crypto-config/ordererOrganizations/emr.com/orderers/orderer.emr.com/tls/server.crt
  BatchTimeout: 2s
  BatchSize:
    MaxMessageCount: 10
    AbsoluteMaxBytes: 99 MB
    PreferredMaxBytes: 512 KB
  Organizations:
  Policies:
    Readers:
      Type: ImplicitMeta
      Rule: "ANY Readers"
    Writers:
      Type: ImplicitMeta
      Rule: "ANY Writers"
    Admins:
      Type: ImplicitMeta
      Rule: "MAJORITY Admins"
    BlockValidation:
      Type: ImplicitMeta
      Rule: "ANY Writers"
  Capabilities:
    <<: *OrdererCapabilities

Channel: &ChannelDefaults
  Policies:
    Readers:
      Type: ImplicitMeta
      Rule: "ANY Readers"
    Writers:
      Type: ImplicitMeta
      Rule: "ANY Writers"
    Admins:
      Type: ImplicitMeta
      Rule: "MAJORITY Admins"
  Capabilities:
    <<: *ChannelCapabilities

Profiles:
  # Genesis block profile for system channel
  EMROrdererGenesis:
    <<: *ChannelDefaults
    Orderer:
      <<: *OrdererDefaults
      Organizations:
        - *OrdererOrg
      Capabilities: *OrdererCapabilities
    Application:
      <<: *ApplicationDefaults
      Organizations:
        - *Hospital1
        - *Hospital2
        - *Regulator
      Capabilities: *ApplicationCapabilities

  # Channel profile for EMR application channel
  EMRChannel:
    Consortium: SampleConsortium
    <<: *ChannelDefaults
    Application:
      <<: *ApplicationDefaults
      Organizations:
        - *Hospital1
        - *Hospital2
        - *Regulator
      Capabilities: *ApplicationCapabilities

  # System channel profile
  SampleMultiNodeEtcdRaft:
    <<: *ChannelDefaults
    Capabilities:
      <<: *ChannelCapabilities
    Orderer:
      <<: *OrdererDefaults
      Organizations:
        - *OrdererOrg
      Capabilities:
        <<: *OrdererCapabilities
    Consortiums:
      SampleConsortium:
        Organizations:
          - *Hospital1
          - *Hospital2
          - *Regulator
