declare module 'lucide-react' {
  import { ComponentType, SVGProps } from 'react';

  export interface LucideProps extends SVGProps<SVGSVGElement> {
    size?: string | number;
    color?: string;
    strokeWidth?: string | number;
  }

  export type LucideIcon = ComponentType<LucideProps>;

  // Common icons used in the application
  export const Activity: LucideIcon;
  export const AlertCircle: LucideIcon;
  export const AlertTriangle: LucideIcon;
  export const Archive: LucideIcon;
  export const ArrowRightLeft: LucideIcon;
  export const Award: LucideIcon;
  export const BarChart3: LucideIcon;
  export const ArrowLeft: LucideIcon;
  export const ArrowRight: LucideIcon;
  export const Bell: LucideIcon;
  export const Bot: LucideIcon;
  export const Calendar: LucideIcon;
  export const Camera: LucideIcon;
  export const Check: LucideIcon;
  export const CheckCheck: LucideIcon;
  export const CheckCircle2: LucideIcon;
  export const CheckCircle: LucideIcon;
  export const ChevronDown: LucideIcon;
  export const ChevronLeft: LucideIcon;
  export const ChevronRight: LucideIcon;
  export const ChevronUp: LucideIcon;
  export const Clock: LucideIcon;
  export const Cloud: LucideIcon;
  export const Command: LucideIcon;
  export const Cpu: LucideIcon;
  export const Database: LucideIcon;
  export const Download: LucideIcon;
  export const Edit: LucideIcon;
  export const Edit3: LucideIcon;
  export const Eye: LucideIcon;
  export const EyeOff: LucideIcon;
  export const File: LucideIcon;
  export const FileText: LucideIcon;
  export const Filter: LucideIcon;
  export const Globe: LucideIcon;
  export const HardDrive: LucideIcon;
  export const History: LucideIcon;
  export const Heart: LucideIcon;
  export const Home: LucideIcon;
  export const Image: LucideIcon;
  export const ImageIcon: LucideIcon;
  export const Info: LucideIcon;
  export const Key: LucideIcon;
  export const Layers: LucideIcon;
  export const Loader2: LucideIcon;
  export const Lock: LucideIcon;
  export const LogOut: LucideIcon;
  export const Mail: LucideIcon;
  export const MapPin: LucideIcon;
  export const Menu: LucideIcon;
  export const MessageCircle: LucideIcon;
  export const Mic: LucideIcon;
  export const Monitor: LucideIcon;
  export const Moon: LucideIcon;
  export const MoreHorizontal: LucideIcon;
  export const MoreVertical: LucideIcon;
  export const Palette: LucideIcon;
  export const Paperclip: LucideIcon;
  export const Phone: LucideIcon;
  export const Plus: LucideIcon;
  export const Refresh: LucideIcon;
  export const RefreshCw: LucideIcon;
  export const Save: LucideIcon;
  export const Search: LucideIcon;
  export const SearchX: LucideIcon;
  export const Send: LucideIcon;
  export const Server: LucideIcon;
  export const Settings: LucideIcon;
  export const Share: LucideIcon;
  export const Shield: LucideIcon;
  export const Star: LucideIcon;
  export const Sun: LucideIcon;
  export const Thermometer: LucideIcon;
  export const Trash: LucideIcon;
  export const Trash2: LucideIcon;
  export const TrendingDown: LucideIcon;
  export const TrendingUp: LucideIcon;
  export const Unlock: LucideIcon;
  export const Upload: LucideIcon;
  export const User: LucideIcon;
  export const UserCheck: LucideIcon;
  export const Users: LucideIcon;
  export const UserX: LucideIcon;
  export const Weight: LucideIcon;
  export const Wifi: LucideIcon;
  export const X: LucideIcon;
  export const XCircle: LucideIcon;
  export const XCircle: LucideIcon;

  // Additional icons used in the application
  export const Keyboard: LucideIcon;
  export const Volume2: LucideIcon;
  export const Accessibility: LucideIcon;
  export const ShieldCheck: LucideIcon;
  export const Palette: LucideIcon;
  export const ArrowRightLeft: LucideIcon;
  export const Award: LucideIcon;
  export const Bot: LucideIcon;
  export const Brain: LucideIcon;
  export const Building: LucideIcon;
  export const Camera: LucideIcon;
  export const CheckCheck: LucideIcon;
  export const CheckCircle2: LucideIcon;
  export const Cloud: LucideIcon;
  export const Command: LucideIcon;
  export const Cpu: LucideIcon;
  export const Database: LucideIcon;
  export const Edit3: LucideIcon;
  export const ExternalLink: LucideIcon;
  export const File: LucideIcon;
  export const HardDrive: LucideIcon;
  export const History: LucideIcon;
  export const Image: LucideIcon;
  export const ImageIcon: LucideIcon;
  export const Key: LucideIcon;
  export const Loader2: LucideIcon;
  export const MapPin: LucideIcon;
  export const MessageCircle: LucideIcon;
  export const Mic: LucideIcon;
  export const Paperclip: LucideIcon;
  export const Phone: LucideIcon;
  export const RefreshCw: LucideIcon;
  export const SearchX: LucideIcon;
  export const Send: LucideIcon;
  export const Server: LucideIcon;
  export const Share2: LucideIcon;
  export const Stethoscope: LucideIcon;
  export const Thermometer: LucideIcon;
  export const Trash2: LucideIcon;
  export const TrendingUp: LucideIcon;
  export const UserCheck: LucideIcon;
  export const UserX: LucideIcon;
  export const Weight: LucideIcon;
  export const Wifi: LucideIcon;
  export const Zap: LucideIcon;
  export const Share2: LucideIcon;

  // Add any other icons as needed
  const lucideReact: {
    [key: string]: LucideIcon;
  };

  export default lucideReact;
}
